#!/usr/bin/env python3
import parser.parse as p
p.table = {
	"\x19 ::=  ● re \x18": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": "elemre ::= RBRAC ● ",
		"CARET": "elemre ::= CARET ● ",
		"LPAREN": "group ::= LPAREN ● re RPAREN",
		"RPAREN": None,
		"WILDCARD": "any ::= WILDCARD ● ",
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": "posset ::= LBRAC ● setitems RBRAC",
		"HYPHEN": None,
		"\x18": None,
		"re": "\x19 ::= re ● \x18",
		"union": "re ::= union ● ",
		"simplere": "re ::= simplere ● ",
		"concat": "simplere ::= concat ● ",
		"basicre": "simplere ::= basicre ● ",
		"star": "basicre ::= star ● ",
		"plus": "basicre ::= plus ● ",
		"question": "basicre ::= question ● ",
		"elemre": "basicre ::= elemre ● ",
		"group": "elemre ::= group ● ",
		"any": "elemre ::= any ● ",
		"char": "elemre ::= char ● ",
		"set": "elemre ::= set ● ",
		"posset": "set ::= posset ● ",
		"negset": "set ::= negset ● ",
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"\x19 ::= re ● \x18": {
		"ALTERNATE": "union ::= re ALTERNATE ● simplere",
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": None,
		"CARET": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"LETTER": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"LBRAC": None,
		"HYPHEN": None,
		"\x18": "accept",
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"union ::= re ALTERNATE ● simplere": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": "elemre ::= RBRAC ● ",
		"CARET": "elemre ::= CARET ● ",
		"LPAREN": "group ::= LPAREN ● re RPAREN",
		"RPAREN": None,
		"WILDCARD": "any ::= WILDCARD ● ",
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": "posset ::= LBRAC ● setitems RBRAC",
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": "union ::= re ALTERNATE simplere ● ",
		"concat": "simplere ::= concat ● ",
		"basicre": "simplere ::= basicre ● ",
		"star": "basicre ::= star ● ",
		"plus": "basicre ::= plus ● ",
		"question": "basicre ::= question ● ",
		"elemre": "basicre ::= elemre ● ",
		"group": "elemre ::= group ● ",
		"any": "elemre ::= any ● ",
		"char": "elemre ::= char ● ",
		"set": "elemre ::= set ● ",
		"posset": "set ::= posset ● ",
		"negset": "set ::= negset ● ",
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"union ::= re ALTERNATE simplere ● ": {
		"ALTERNATE": ('union', 3),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": "elemre ::= RBRAC ● ",
		"CARET": "elemre ::= CARET ● ",
		"LPAREN": "group ::= LPAREN ● re RPAREN",
		"RPAREN": ('union', 3),
		"WILDCARD": "any ::= WILDCARD ● ",
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": "posset ::= LBRAC ● setitems RBRAC",
		"HYPHEN": None,
		"\x18": ('union', 3),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": "concat ::= simplere basicre ● ",
		"star": "basicre ::= star ● ",
		"plus": "basicre ::= plus ● ",
		"question": "basicre ::= question ● ",
		"elemre": "basicre ::= elemre ● ",
		"group": "elemre ::= group ● ",
		"any": "elemre ::= any ● ",
		"char": "elemre ::= char ● ",
		"set": "elemre ::= set ● ",
		"posset": "set ::= posset ● ",
		"negset": "set ::= negset ● ",
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"concat ::= simplere basicre ● ": {
		"ALTERNATE": ('concat', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('concat', 2),
		"CARET": ('concat', 2),
		"LPAREN": ('concat', 2),
		"RPAREN": ('concat', 2),
		"WILDCARD": ('concat', 2),
		"LETTER": ('concat', 2),
		"NEWLINE": ('concat', 2),
		"SPACE": ('concat', 2),
		"BSLASH": ('concat', 2),
		"SQUOTE": ('concat', 2),
		"DQUOTE": ('concat', 2),
		"TAB": ('concat', 2),
		"LBRAC": ('concat', 2),
		"HYPHEN": None,
		"\x18": ('concat', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre ::= star ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('basicre', 1),
		"CARET": ('basicre', 1),
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"LETTER": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"SPACE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"SQUOTE": ('basicre', 1),
		"DQUOTE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre ::= plus ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('basicre', 1),
		"CARET": ('basicre', 1),
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"LETTER": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"SPACE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"SQUOTE": ('basicre', 1),
		"DQUOTE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre ::= question ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('basicre', 1),
		"CARET": ('basicre', 1),
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"LETTER": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"SPACE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"SQUOTE": ('basicre', 1),
		"DQUOTE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre ::= elemre ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": "star ::= elemre KLEENE ● ",
		"PLUS": "plus ::= elemre PLUS ● ",
		"QUESTION": "question ::= elemre QUESTION ● ",
		"RBRAC": ('basicre', 1),
		"CARET": ('basicre', 1),
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"LETTER": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"SPACE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"SQUOTE": ('basicre', 1),
		"DQUOTE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"star ::= elemre KLEENE ● ": {
		"ALTERNATE": ('star', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('star', 2),
		"CARET": ('star', 2),
		"LPAREN": ('star', 2),
		"RPAREN": ('star', 2),
		"WILDCARD": ('star', 2),
		"LETTER": ('star', 2),
		"NEWLINE": ('star', 2),
		"SPACE": ('star', 2),
		"BSLASH": ('star', 2),
		"SQUOTE": ('star', 2),
		"DQUOTE": ('star', 2),
		"TAB": ('star', 2),
		"LBRAC": ('star', 2),
		"HYPHEN": None,
		"\x18": ('star', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"plus ::= elemre PLUS ● ": {
		"ALTERNATE": ('plus', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('plus', 2),
		"CARET": ('plus', 2),
		"LPAREN": ('plus', 2),
		"RPAREN": ('plus', 2),
		"WILDCARD": ('plus', 2),
		"LETTER": ('plus', 2),
		"NEWLINE": ('plus', 2),
		"SPACE": ('plus', 2),
		"BSLASH": ('plus', 2),
		"SQUOTE": ('plus', 2),
		"DQUOTE": ('plus', 2),
		"TAB": ('plus', 2),
		"LBRAC": ('plus', 2),
		"HYPHEN": None,
		"\x18": ('plus', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"question ::= elemre QUESTION ● ": {
		"ALTERNATE": ('question', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('question', 2),
		"CARET": ('question', 2),
		"LPAREN": ('question', 2),
		"RPAREN": ('question', 2),
		"WILDCARD": ('question', 2),
		"LETTER": ('question', 2),
		"NEWLINE": ('question', 2),
		"SPACE": ('question', 2),
		"BSLASH": ('question', 2),
		"SQUOTE": ('question', 2),
		"DQUOTE": ('question', 2),
		"TAB": ('question', 2),
		"LBRAC": ('question', 2),
		"HYPHEN": None,
		"\x18": ('question', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre ::= group ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"RBRAC": ('elemre', 1),
		"CARET": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"LETTER": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre ::= any ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"RBRAC": ('elemre', 1),
		"CARET": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"LETTER": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre ::= char ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"RBRAC": ('elemre', 1),
		"CARET": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"LETTER": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre ::= set ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"RBRAC": ('elemre', 1),
		"CARET": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"LETTER": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"set ::= posset ● ": {
		"ALTERNATE": ('set', 1),
		"KLEENE": ('set', 1),
		"PLUS": ('set', 1),
		"QUESTION": ('set', 1),
		"RBRAC": ('set', 1),
		"CARET": ('set', 1),
		"LPAREN": ('set', 1),
		"RPAREN": ('set', 1),
		"WILDCARD": ('set', 1),
		"LETTER": ('set', 1),
		"NEWLINE": ('set', 1),
		"SPACE": ('set', 1),
		"BSLASH": ('set', 1),
		"SQUOTE": ('set', 1),
		"DQUOTE": ('set', 1),
		"TAB": ('set', 1),
		"LBRAC": ('set', 1),
		"HYPHEN": None,
		"\x18": ('set', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"set ::= negset ● ": {
		"ALTERNATE": ('set', 1),
		"KLEENE": ('set', 1),
		"PLUS": ('set', 1),
		"QUESTION": ('set', 1),
		"RBRAC": ('set', 1),
		"CARET": ('set', 1),
		"LPAREN": ('set', 1),
		"RPAREN": ('set', 1),
		"WILDCARD": ('set', 1),
		"LETTER": ('set', 1),
		"NEWLINE": ('set', 1),
		"SPACE": ('set', 1),
		"BSLASH": ('set', 1),
		"SQUOTE": ('set', 1),
		"DQUOTE": ('set', 1),
		"TAB": ('set', 1),
		"LBRAC": ('set', 1),
		"HYPHEN": None,
		"\x18": ('set', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre ::= RBRAC ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"RBRAC": ('elemre', 1),
		"CARET": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"LETTER": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre ::= CARET ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"RBRAC": ('elemre', 1),
		"CARET": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"LETTER": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"group ::= LPAREN ● re RPAREN": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": "elemre ::= RBRAC ● ",
		"CARET": "elemre ::= CARET ● ",
		"LPAREN": "group ::= LPAREN ● re RPAREN",
		"RPAREN": None,
		"WILDCARD": "any ::= WILDCARD ● ",
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": "posset ::= LBRAC ● setitems RBRAC",
		"HYPHEN": None,
		"\x18": None,
		"re": "group ::= LPAREN re ● RPAREN",
		"union": "re ::= union ● ",
		"simplere": "re ::= simplere ● ",
		"concat": "simplere ::= concat ● ",
		"basicre": "simplere ::= basicre ● ",
		"star": "basicre ::= star ● ",
		"plus": "basicre ::= plus ● ",
		"question": "basicre ::= question ● ",
		"elemre": "basicre ::= elemre ● ",
		"group": "elemre ::= group ● ",
		"any": "elemre ::= any ● ",
		"char": "elemre ::= char ● ",
		"set": "elemre ::= set ● ",
		"posset": "set ::= posset ● ",
		"negset": "set ::= negset ● ",
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"group ::= LPAREN re ● RPAREN": {
		"ALTERNATE": "union ::= re ALTERNATE ● simplere",
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": None,
		"CARET": None,
		"LPAREN": None,
		"RPAREN": "group ::= LPAREN re RPAREN ● ",
		"WILDCARD": None,
		"LETTER": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"LBRAC": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"group ::= LPAREN re RPAREN ● ": {
		"ALTERNATE": ('group', 3),
		"KLEENE": ('group', 3),
		"PLUS": ('group', 3),
		"QUESTION": ('group', 3),
		"RBRAC": ('group', 3),
		"CARET": ('group', 3),
		"LPAREN": ('group', 3),
		"RPAREN": ('group', 3),
		"WILDCARD": ('group', 3),
		"LETTER": ('group', 3),
		"NEWLINE": ('group', 3),
		"SPACE": ('group', 3),
		"BSLASH": ('group', 3),
		"SQUOTE": ('group', 3),
		"DQUOTE": ('group', 3),
		"TAB": ('group', 3),
		"LBRAC": ('group', 3),
		"HYPHEN": None,
		"\x18": ('group', 3),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"re ::= union ● ": {
		"ALTERNATE": ('re', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": None,
		"CARET": None,
		"LPAREN": None,
		"RPAREN": ('re', 1),
		"WILDCARD": None,
		"LETTER": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"LBRAC": None,
		"HYPHEN": None,
		"\x18": ('re', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"re ::= simplere ● ": {
		"ALTERNATE": ('re', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": "elemre ::= RBRAC ● ",
		"CARET": "elemre ::= CARET ● ",
		"LPAREN": "group ::= LPAREN ● re RPAREN",
		"RPAREN": ('re', 1),
		"WILDCARD": "any ::= WILDCARD ● ",
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": "posset ::= LBRAC ● setitems RBRAC",
		"HYPHEN": None,
		"\x18": ('re', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": "concat ::= simplere basicre ● ",
		"star": "basicre ::= star ● ",
		"plus": "basicre ::= plus ● ",
		"question": "basicre ::= question ● ",
		"elemre": "basicre ::= elemre ● ",
		"group": "elemre ::= group ● ",
		"any": "elemre ::= any ● ",
		"char": "elemre ::= char ● ",
		"set": "elemre ::= set ● ",
		"posset": "set ::= posset ● ",
		"negset": "set ::= negset ● ",
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"any ::= WILDCARD ● ": {
		"ALTERNATE": ('any', 1),
		"KLEENE": ('any', 1),
		"PLUS": ('any', 1),
		"QUESTION": ('any', 1),
		"RBRAC": ('any', 1),
		"CARET": ('any', 1),
		"LPAREN": ('any', 1),
		"RPAREN": ('any', 1),
		"WILDCARD": ('any', 1),
		"LETTER": ('any', 1),
		"NEWLINE": ('any', 1),
		"SPACE": ('any', 1),
		"BSLASH": ('any', 1),
		"SQUOTE": ('any', 1),
		"DQUOTE": ('any', 1),
		"TAB": ('any', 1),
		"LBRAC": ('any', 1),
		"HYPHEN": None,
		"\x18": ('any', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"char ::= LETTER ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"LETTER": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"LBRAC": ('char', 1),
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"char ::= NEWLINE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"LETTER": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"LBRAC": ('char', 1),
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"char ::= SPACE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"LETTER": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"LBRAC": ('char', 1),
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"char ::= BSLASH ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"LETTER": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"LBRAC": ('char', 1),
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"char ::= SQUOTE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"LETTER": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"LBRAC": ('char', 1),
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"char ::= DQUOTE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"LETTER": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"LBRAC": ('char', 1),
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"char ::= TAB ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"LETTER": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"LBRAC": ('char', 1),
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"posset ::= LBRAC ● setitems RBRAC": {
		"ALTERNATE": "setitem ::= ALTERNATE ● ",
		"KLEENE": "setitem ::= KLEENE ● ",
		"PLUS": "setitem ::= PLUS ● ",
		"QUESTION": "setitem ::= QUESTION ● ",
		"RBRAC": None,
		"CARET": "negset ::= LBRAC CARET ● negsetitems RBRAC",
		"LPAREN": "setitem ::= LPAREN ● ",
		"RPAREN": "setitem ::= RPAREN ● ",
		"WILDCARD": "setitem ::= WILDCARD ● ",
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": "setitem ::= LBRAC ● ",
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem ::= char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": "posset ::= LBRAC setitems ● RBRAC",
		"setitem": "setitems ::= setitem ● ",
		"negsetitems": None,
		"negsetitem": None,
		"range": "setitem ::= range ● ",
		"\x19": None,
	},
	"setitem ::= char ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": "range ::= char HYPHEN ● char",
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"range ::= char HYPHEN ● char": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": None,
		"CARET": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "range ::= char HYPHEN char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"range ::= char HYPHEN char ● ": {
		"ALTERNATE": ('range', 3),
		"KLEENE": ('range', 3),
		"PLUS": ('range', 3),
		"QUESTION": ('range', 3),
		"RBRAC": ('range', 3),
		"CARET": ('range', 3),
		"LPAREN": ('range', 3),
		"RPAREN": ('range', 3),
		"WILDCARD": ('range', 3),
		"LETTER": ('range', 3),
		"NEWLINE": ('range', 3),
		"SPACE": ('range', 3),
		"BSLASH": ('range', 3),
		"SQUOTE": ('range', 3),
		"DQUOTE": ('range', 3),
		"TAB": ('range', 3),
		"LBRAC": ('range', 3),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"posset ::= LBRAC setitems ● RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": "posset ::= LBRAC setitems RBRAC ● ",
		"CARET": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"LETTER": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"LBRAC": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"posset ::= LBRAC setitems RBRAC ● ": {
		"ALTERNATE": ('posset', 3),
		"KLEENE": ('posset', 3),
		"PLUS": ('posset', 3),
		"QUESTION": ('posset', 3),
		"RBRAC": ('posset', 3),
		"CARET": ('posset', 3),
		"LPAREN": ('posset', 3),
		"RPAREN": ('posset', 3),
		"WILDCARD": ('posset', 3),
		"LETTER": ('posset', 3),
		"NEWLINE": ('posset', 3),
		"SPACE": ('posset', 3),
		"BSLASH": ('posset', 3),
		"SQUOTE": ('posset', 3),
		"DQUOTE": ('posset', 3),
		"TAB": ('posset', 3),
		"LBRAC": ('posset', 3),
		"HYPHEN": None,
		"\x18": ('posset', 3),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitems ::= setitem ● ": {
		"ALTERNATE": "setitem ::= ALTERNATE ● ",
		"KLEENE": "setitem ::= KLEENE ● ",
		"PLUS": "setitem ::= PLUS ● ",
		"QUESTION": "setitem ::= QUESTION ● ",
		"RBRAC": ('setitems', 1),
		"CARET": "negsetitem ::= CARET ● ",
		"LPAREN": "setitem ::= LPAREN ● ",
		"RPAREN": "setitem ::= RPAREN ● ",
		"WILDCARD": "setitem ::= WILDCARD ● ",
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": "setitem ::= LBRAC ● ",
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem ::= char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": "negsetitem ::= setitem ● ",
		"negsetitems": "setitems ::= setitem negsetitems ● ",
		"negsetitem": "negsetitems ::= negsetitem ● ",
		"range": "setitem ::= range ● ",
		"\x19": None,
	},
	"negsetitem ::= setitem ● ": {
		"ALTERNATE": ('negsetitem', 1),
		"KLEENE": ('negsetitem', 1),
		"PLUS": ('negsetitem', 1),
		"QUESTION": ('negsetitem', 1),
		"RBRAC": ('negsetitem', 1),
		"CARET": ('negsetitem', 1),
		"LPAREN": ('negsetitem', 1),
		"RPAREN": ('negsetitem', 1),
		"WILDCARD": ('negsetitem', 1),
		"LETTER": ('negsetitem', 1),
		"NEWLINE": ('negsetitem', 1),
		"SPACE": ('negsetitem', 1),
		"BSLASH": ('negsetitem', 1),
		"SQUOTE": ('negsetitem', 1),
		"DQUOTE": ('negsetitem', 1),
		"TAB": ('negsetitem', 1),
		"LBRAC": ('negsetitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitems ::= setitem negsetitems ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('setitems', 2),
		"CARET": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"LETTER": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"LBRAC": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"negsetitems ::= negsetitem ● ": {
		"ALTERNATE": "setitem ::= ALTERNATE ● ",
		"KLEENE": "setitem ::= KLEENE ● ",
		"PLUS": "setitem ::= PLUS ● ",
		"QUESTION": "setitem ::= QUESTION ● ",
		"RBRAC": ('negsetitems', 1),
		"CARET": "negsetitem ::= CARET ● ",
		"LPAREN": "setitem ::= LPAREN ● ",
		"RPAREN": "setitem ::= RPAREN ● ",
		"WILDCARD": "setitem ::= WILDCARD ● ",
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": "setitem ::= LBRAC ● ",
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem ::= char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": "negsetitem ::= setitem ● ",
		"negsetitems": "negsetitems ::= negsetitem negsetitems ● ",
		"negsetitem": "negsetitems ::= negsetitem ● ",
		"range": "setitem ::= range ● ",
		"\x19": None,
	},
	"negsetitems ::= negsetitem negsetitems ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('negsetitems', 2),
		"CARET": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"LETTER": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"LBRAC": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem ::= range ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem ::= ALTERNATE ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem ::= KLEENE ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem ::= PLUS ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem ::= QUESTION ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"negsetitem ::= CARET ● ": {
		"ALTERNATE": ('negsetitem', 1),
		"KLEENE": ('negsetitem', 1),
		"PLUS": ('negsetitem', 1),
		"QUESTION": ('negsetitem', 1),
		"RBRAC": ('negsetitem', 1),
		"CARET": ('negsetitem', 1),
		"LPAREN": ('negsetitem', 1),
		"RPAREN": ('negsetitem', 1),
		"WILDCARD": ('negsetitem', 1),
		"LETTER": ('negsetitem', 1),
		"NEWLINE": ('negsetitem', 1),
		"SPACE": ('negsetitem', 1),
		"BSLASH": ('negsetitem', 1),
		"SQUOTE": ('negsetitem', 1),
		"DQUOTE": ('negsetitem', 1),
		"TAB": ('negsetitem', 1),
		"LBRAC": ('negsetitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem ::= LPAREN ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem ::= RPAREN ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem ::= WILDCARD ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem ::= LBRAC ● ": {
		"ALTERNATE": ('setitem', 1),
		"KLEENE": ('setitem', 1),
		"PLUS": ('setitem', 1),
		"QUESTION": ('setitem', 1),
		"RBRAC": ('setitem', 1),
		"CARET": ('setitem', 1),
		"LPAREN": ('setitem', 1),
		"RPAREN": ('setitem', 1),
		"WILDCARD": ('setitem', 1),
		"LETTER": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"LBRAC": ('setitem', 1),
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"negset ::= LBRAC CARET ● negsetitems RBRAC": {
		"ALTERNATE": "setitem ::= ALTERNATE ● ",
		"KLEENE": "setitem ::= KLEENE ● ",
		"PLUS": "setitem ::= PLUS ● ",
		"QUESTION": "setitem ::= QUESTION ● ",
		"RBRAC": None,
		"CARET": "negsetitem ::= CARET ● ",
		"LPAREN": "setitem ::= LPAREN ● ",
		"RPAREN": "setitem ::= RPAREN ● ",
		"WILDCARD": "setitem ::= WILDCARD ● ",
		"LETTER": "char ::= LETTER ● ",
		"NEWLINE": "char ::= NEWLINE ● ",
		"SPACE": "char ::= SPACE ● ",
		"BSLASH": "char ::= BSLASH ● ",
		"SQUOTE": "char ::= SQUOTE ● ",
		"DQUOTE": "char ::= DQUOTE ● ",
		"TAB": "char ::= TAB ● ",
		"LBRAC": "setitem ::= LBRAC ● ",
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem ::= char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": "negsetitem ::= setitem ● ",
		"negsetitems": "negset ::= LBRAC CARET negsetitems ● RBRAC",
		"negsetitem": "negsetitems ::= negsetitem ● ",
		"range": "setitem ::= range ● ",
		"\x19": None,
	},
	"negset ::= LBRAC CARET negsetitems ● RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": "negset ::= LBRAC CARET negsetitems RBRAC ● ",
		"CARET": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"LETTER": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"LBRAC": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"negset ::= LBRAC CARET negsetitems RBRAC ● ": {
		"ALTERNATE": ('negset', 4),
		"KLEENE": ('negset', 4),
		"PLUS": ('negset', 4),
		"QUESTION": ('negset', 4),
		"RBRAC": ('negset', 4),
		"CARET": ('negset', 4),
		"LPAREN": ('negset', 4),
		"RPAREN": ('negset', 4),
		"WILDCARD": ('negset', 4),
		"LETTER": ('negset', 4),
		"NEWLINE": ('negset', 4),
		"SPACE": ('negset', 4),
		"BSLASH": ('negset', 4),
		"SQUOTE": ('negset', 4),
		"DQUOTE": ('negset', 4),
		"TAB": ('negset', 4),
		"LBRAC": ('negset', 4),
		"HYPHEN": None,
		"\x18": ('negset', 4),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"simplere ::= concat ● ": {
		"ALTERNATE": ('simplere', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('simplere', 1),
		"CARET": ('simplere', 1),
		"LPAREN": ('simplere', 1),
		"RPAREN": ('simplere', 1),
		"WILDCARD": ('simplere', 1),
		"LETTER": ('simplere', 1),
		"NEWLINE": ('simplere', 1),
		"SPACE": ('simplere', 1),
		"BSLASH": ('simplere', 1),
		"SQUOTE": ('simplere', 1),
		"DQUOTE": ('simplere', 1),
		"TAB": ('simplere', 1),
		"LBRAC": ('simplere', 1),
		"HYPHEN": None,
		"\x18": ('simplere', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
	"simplere ::= basicre ● ": {
		"ALTERNATE": ('simplere', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"RBRAC": ('simplere', 1),
		"CARET": ('simplere', 1),
		"LPAREN": ('simplere', 1),
		"RPAREN": ('simplere', 1),
		"WILDCARD": ('simplere', 1),
		"LETTER": ('simplere', 1),
		"NEWLINE": ('simplere', 1),
		"SPACE": ('simplere', 1),
		"BSLASH": ('simplere', 1),
		"SQUOTE": ('simplere', 1),
		"DQUOTE": ('simplere', 1),
		"TAB": ('simplere', 1),
		"LBRAC": ('simplere', 1),
		"HYPHEN": None,
		"\x18": ('simplere', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"negsetitems": None,
		"negsetitem": None,
		"range": None,
		"\x19": None,
	},
}
p.start = list(p.table.keys())[0]
