#!/usr/bin/env python3
import parser.parse as p
import RegexTree as RT

p.table = {
	"\x19 :=  ● re \x18": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": None,
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"N": "char := N ● ",
		"T": "char := T ● ",
		"R": "char := R ● ",
		"UNDERSCORE": "char := UNDERSCORE ● ",
		"BSLASH": "char := BSLASH ● LPAREN",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": "\x19 := re ● \x18",
		"union": "re := union ● ",
		"simplere": "re := simplere ● ",
		"concat": "simplere := concat ● ",
		"basicre": "simplere := basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"\x19 := re ● \x18": {
		"ALTERNATE": "union := re ALTERNATE ● simplere",
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"TAB": None,
		"RETURN": None,
		"N": None,
		"T": None,
		"R": None,
		"UNDERSCORE": None,
		"BSLASH": None,
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": "accept",
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"union := re ALTERNATE ● simplere": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": None,
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"N": "char := N ● ",
		"T": "char := T ● ",
		"R": "char := R ● ",
		"UNDERSCORE": "char := UNDERSCORE ● ",
		"BSLASH": "char := BSLASH ● LPAREN",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": "union := re ALTERNATE simplere ● ",
		"concat": "simplere := concat ● ",
		"basicre": "simplere := basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"union := re ALTERNATE simplere ● ": {
		"ALTERNATE": ('union', 3),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": ('union', 3),
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"N": "char := N ● ",
		"T": "char := T ● ",
		"R": "char := R ● ",
		"UNDERSCORE": "char := UNDERSCORE ● ",
		"BSLASH": "char := BSLASH ● LPAREN",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('union', 3),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": "concat := simplere basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"concat := simplere basicre ● ": {
		"ALTERNATE": ('concat', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('concat', 2),
		"RPAREN": ('concat', 2),
		"WILDCARD": ('concat', 2),
		"CHAR": ('concat', 2),
		"NEWLINE": ('concat', 2),
		"TAB": ('concat', 2),
		"RETURN": ('concat', 2),
		"N": ('concat', 2),
		"T": ('concat', 2),
		"R": ('concat', 2),
		"UNDERSCORE": ('concat', 2),
		"BSLASH": ('concat', 2),
		"LBRAC": ('concat', 2),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('concat', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre := star ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"CHAR": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"RETURN": ('basicre', 1),
		"N": ('basicre', 1),
		"T": ('basicre', 1),
		"R": ('basicre', 1),
		"UNDERSCORE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre := plus ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"CHAR": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"RETURN": ('basicre', 1),
		"N": ('basicre', 1),
		"T": ('basicre', 1),
		"R": ('basicre', 1),
		"UNDERSCORE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre := question ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"CHAR": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"RETURN": ('basicre', 1),
		"N": ('basicre', 1),
		"T": ('basicre', 1),
		"R": ('basicre', 1),
		"UNDERSCORE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre := elemre ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": "star := elemre KLEENE ● ",
		"PLUS": "plus := elemre PLUS ● ",
		"QUESTION": "question := elemre QUESTION ● ",
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"CHAR": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"RETURN": ('basicre', 1),
		"N": ('basicre', 1),
		"T": ('basicre', 1),
		"R": ('basicre', 1),
		"UNDERSCORE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"star := elemre KLEENE ● ": {
		"ALTERNATE": ('star', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('star', 2),
		"RPAREN": ('star', 2),
		"WILDCARD": ('star', 2),
		"CHAR": ('star', 2),
		"NEWLINE": ('star', 2),
		"TAB": ('star', 2),
		"RETURN": ('star', 2),
		"N": ('star', 2),
		"T": ('star', 2),
		"R": ('star', 2),
		"UNDERSCORE": ('star', 2),
		"BSLASH": ('star', 2),
		"LBRAC": ('star', 2),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('star', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"plus := elemre PLUS ● ": {
		"ALTERNATE": ('plus', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('plus', 2),
		"RPAREN": ('plus', 2),
		"WILDCARD": ('plus', 2),
		"CHAR": ('plus', 2),
		"NEWLINE": ('plus', 2),
		"TAB": ('plus', 2),
		"RETURN": ('plus', 2),
		"N": ('plus', 2),
		"T": ('plus', 2),
		"R": ('plus', 2),
		"UNDERSCORE": ('plus', 2),
		"BSLASH": ('plus', 2),
		"LBRAC": ('plus', 2),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('plus', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"question := elemre QUESTION ● ": {
		"ALTERNATE": ('question', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('question', 2),
		"RPAREN": ('question', 2),
		"WILDCARD": ('question', 2),
		"CHAR": ('question', 2),
		"NEWLINE": ('question', 2),
		"TAB": ('question', 2),
		"RETURN": ('question', 2),
		"N": ('question', 2),
		"T": ('question', 2),
		"R": ('question', 2),
		"UNDERSCORE": ('question', 2),
		"BSLASH": ('question', 2),
		"LBRAC": ('question', 2),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('question', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre := group ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"CHAR": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"RETURN": ('elemre', 1),
		"N": ('elemre', 1),
		"T": ('elemre', 1),
		"R": ('elemre', 1),
		"UNDERSCORE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre := any ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"CHAR": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"RETURN": ('elemre', 1),
		"N": ('elemre', 1),
		"T": ('elemre', 1),
		"R": ('elemre', 1),
		"UNDERSCORE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre := char ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"CHAR": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"RETURN": ('elemre', 1),
		"N": ('elemre', 1),
		"T": ('elemre', 1),
		"R": ('elemre', 1),
		"UNDERSCORE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre := set ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"CHAR": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"RETURN": ('elemre', 1),
		"N": ('elemre', 1),
		"T": ('elemre', 1),
		"R": ('elemre', 1),
		"UNDERSCORE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"set := posset ● ": {
		"ALTERNATE": ('set', 1),
		"KLEENE": ('set', 1),
		"PLUS": ('set', 1),
		"QUESTION": ('set', 1),
		"LPAREN": ('set', 1),
		"RPAREN": ('set', 1),
		"WILDCARD": ('set', 1),
		"CHAR": ('set', 1),
		"NEWLINE": ('set', 1),
		"TAB": ('set', 1),
		"RETURN": ('set', 1),
		"N": ('set', 1),
		"T": ('set', 1),
		"R": ('set', 1),
		"UNDERSCORE": ('set', 1),
		"BSLASH": ('set', 1),
		"LBRAC": ('set', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('set', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"set := negset ● ": {
		"ALTERNATE": ('set', 1),
		"KLEENE": ('set', 1),
		"PLUS": ('set', 1),
		"QUESTION": ('set', 1),
		"LPAREN": ('set', 1),
		"RPAREN": ('set', 1),
		"WILDCARD": ('set', 1),
		"CHAR": ('set', 1),
		"NEWLINE": ('set', 1),
		"TAB": ('set', 1),
		"RETURN": ('set', 1),
		"N": ('set', 1),
		"T": ('set', 1),
		"R": ('set', 1),
		"UNDERSCORE": ('set', 1),
		"BSLASH": ('set', 1),
		"LBRAC": ('set', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('set', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"group := LPAREN ● re RPAREN": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": None,
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"N": "char := N ● ",
		"T": "char := T ● ",
		"R": "char := R ● ",
		"UNDERSCORE": "char := UNDERSCORE ● ",
		"BSLASH": "char := BSLASH ● LPAREN",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": "group := LPAREN re ● RPAREN",
		"union": "re := union ● ",
		"simplere": "re := simplere ● ",
		"concat": "simplere := concat ● ",
		"basicre": "simplere := basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"group := LPAREN re ● RPAREN": {
		"ALTERNATE": "union := re ALTERNATE ● simplere",
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": "group := LPAREN re RPAREN ● ",
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"TAB": None,
		"RETURN": None,
		"N": None,
		"T": None,
		"R": None,
		"UNDERSCORE": None,
		"BSLASH": None,
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"group := LPAREN re RPAREN ● ": {
		"ALTERNATE": ('group', 3),
		"KLEENE": ('group', 3),
		"PLUS": ('group', 3),
		"QUESTION": ('group', 3),
		"LPAREN": ('group', 3),
		"RPAREN": ('group', 3),
		"WILDCARD": ('group', 3),
		"CHAR": ('group', 3),
		"NEWLINE": ('group', 3),
		"TAB": ('group', 3),
		"RETURN": ('group', 3),
		"N": ('group', 3),
		"T": ('group', 3),
		"R": ('group', 3),
		"UNDERSCORE": ('group', 3),
		"BSLASH": ('group', 3),
		"LBRAC": ('group', 3),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('group', 3),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"re := union ● ": {
		"ALTERNATE": ('re', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": ('re', 1),
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"TAB": None,
		"RETURN": None,
		"N": None,
		"T": None,
		"R": None,
		"UNDERSCORE": None,
		"BSLASH": None,
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('re', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"re := simplere ● ": {
		"ALTERNATE": ('re', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": ('re', 1),
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"N": "char := N ● ",
		"T": "char := T ● ",
		"R": "char := R ● ",
		"UNDERSCORE": "char := UNDERSCORE ● ",
		"BSLASH": "char := BSLASH ● LPAREN",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('re', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": "concat := simplere basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"any := WILDCARD ● ": {
		"ALTERNATE": ('any', 1),
		"KLEENE": ('any', 1),
		"PLUS": ('any', 1),
		"QUESTION": ('any', 1),
		"LPAREN": ('any', 1),
		"RPAREN": ('any', 1),
		"WILDCARD": ('any', 1),
		"CHAR": ('any', 1),
		"NEWLINE": ('any', 1),
		"TAB": ('any', 1),
		"RETURN": ('any', 1),
		"N": ('any', 1),
		"T": ('any', 1),
		"R": ('any', 1),
		"UNDERSCORE": ('any', 1),
		"BSLASH": ('any', 1),
		"LBRAC": ('any', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('any', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := CHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"N": ('char', 1),
		"T": ('char', 1),
		"R": ('char', 1),
		"UNDERSCORE": ('char', 1),
		"BSLASH": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := NEWLINE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"N": ('char', 1),
		"T": ('char', 1),
		"R": ('char', 1),
		"UNDERSCORE": ('char', 1),
		"BSLASH": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := TAB ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"N": ('char', 1),
		"T": ('char', 1),
		"R": ('char', 1),
		"UNDERSCORE": ('char', 1),
		"BSLASH": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := RETURN ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"N": ('char', 1),
		"T": ('char', 1),
		"R": ('char', 1),
		"UNDERSCORE": ('char', 1),
		"BSLASH": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := N ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"N": ('char', 1),
		"T": ('char', 1),
		"R": ('char', 1),
		"UNDERSCORE": ('char', 1),
		"BSLASH": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := T ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"N": ('char', 1),
		"T": ('char', 1),
		"R": ('char', 1),
		"UNDERSCORE": ('char', 1),
		"BSLASH": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := R ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"N": ('char', 1),
		"T": ('char', 1),
		"R": ('char', 1),
		"UNDERSCORE": ('char', 1),
		"BSLASH": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := UNDERSCORE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"N": ('char', 1),
		"T": ('char', 1),
		"R": ('char', 1),
		"UNDERSCORE": ('char', 1),
		"BSLASH": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH ● LPAREN": {
		"ALTERNATE": "char := BSLASH ALTERNATE ● ",
		"KLEENE": "char := BSLASH KLEENE ● ",
		"PLUS": "char := BSLASH PLUS ● ",
		"QUESTION": "char := BSLASH QUESTION ● ",
		"LPAREN": "char := BSLASH LPAREN ● ",
		"RPAREN": "char := BSLASH RPAREN ● ",
		"WILDCARD": "char := BSLASH WILDCARD ● ",
		"CHAR": None,
		"NEWLINE": None,
		"TAB": None,
		"RETURN": None,
		"N": "char := BSLASH N ● ",
		"T": "char := BSLASH T ● ",
		"R": "char := BSLASH R ● ",
		"UNDERSCORE": "char := BSLASH UNDERSCORE ● ",
		"BSLASH": "char := BSLASH BSLASH ● ",
		"LBRAC": "char := BSLASH LBRAC ● ",
		"RBRAC": "char := BSLASH RBRAC ● ",
		"CARET": "char := BSLASH CARET ● ",
		"HYPHEN": "char := BSLASH HYPHEN ● ",
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH LPAREN ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH RPAREN ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH LBRAC ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH RBRAC ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH KLEENE ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH PLUS ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH QUESTION ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH CARET ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH HYPHEN ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH WILDCARD ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH ALTERNATE ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH BSLASH ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH UNDERSCORE ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH N ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH T ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH R ● ": {
		"ALTERNATE": ('char', 2),
		"KLEENE": ('char', 2),
		"PLUS": ('char', 2),
		"QUESTION": ('char', 2),
		"LPAREN": ('char', 2),
		"RPAREN": ('char', 2),
		"WILDCARD": ('char', 2),
		"CHAR": ('char', 2),
		"NEWLINE": ('char', 2),
		"TAB": ('char', 2),
		"RETURN": ('char', 2),
		"N": ('char', 2),
		"T": ('char', 2),
		"R": ('char', 2),
		"UNDERSCORE": ('char', 2),
		"BSLASH": ('char', 2),
		"LBRAC": ('char', 2),
		"RBRAC": ('char', 2),
		"CARET": None,
		"HYPHEN": ('char', 2),
		"\x18": ('char', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"posset := LBRAC ● setitems RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"N": "char := N ● ",
		"T": "char := T ● ",
		"R": "char := R ● ",
		"UNDERSCORE": "char := UNDERSCORE ● ",
		"BSLASH": "char := BSLASH ● LPAREN",
		"LBRAC": None,
		"RBRAC": None,
		"CARET": "negset := LBRAC CARET ● setitems RBRAC",
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem := char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": "posset := LBRAC setitems ● RBRAC",
		"setitem": "setitems := setitem ● ",
		"range": "setitem := range ● ",
		"\x19": None,
	},
	"setitem := char ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"RETURN": ('setitem', 1),
		"N": ('setitem', 1),
		"T": ('setitem', 1),
		"R": ('setitem', 1),
		"UNDERSCORE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"LBRAC": None,
		"RBRAC": ('setitem', 1),
		"CARET": None,
		"HYPHEN": "range := char HYPHEN ● char",
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"range := char HYPHEN ● char": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"N": "char := N ● ",
		"T": "char := T ● ",
		"R": "char := R ● ",
		"UNDERSCORE": "char := UNDERSCORE ● ",
		"BSLASH": "char := BSLASH ● LPAREN",
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "range := char HYPHEN char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"range := char HYPHEN char ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": ('range', 3),
		"NEWLINE": ('range', 3),
		"TAB": ('range', 3),
		"RETURN": ('range', 3),
		"N": ('range', 3),
		"T": ('range', 3),
		"R": ('range', 3),
		"UNDERSCORE": ('range', 3),
		"BSLASH": ('range', 3),
		"LBRAC": None,
		"RBRAC": ('range', 3),
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"posset := LBRAC setitems ● RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"TAB": None,
		"RETURN": None,
		"N": None,
		"T": None,
		"R": None,
		"UNDERSCORE": None,
		"BSLASH": None,
		"LBRAC": None,
		"RBRAC": "posset := LBRAC setitems RBRAC ● ",
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"posset := LBRAC setitems RBRAC ● ": {
		"ALTERNATE": ('posset', 3),
		"KLEENE": ('posset', 3),
		"PLUS": ('posset', 3),
		"QUESTION": ('posset', 3),
		"LPAREN": ('posset', 3),
		"RPAREN": ('posset', 3),
		"WILDCARD": ('posset', 3),
		"CHAR": ('posset', 3),
		"NEWLINE": ('posset', 3),
		"TAB": ('posset', 3),
		"RETURN": ('posset', 3),
		"N": ('posset', 3),
		"T": ('posset', 3),
		"R": ('posset', 3),
		"UNDERSCORE": ('posset', 3),
		"BSLASH": ('posset', 3),
		"LBRAC": ('posset', 3),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('posset', 3),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"setitems := setitem ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"N": "char := N ● ",
		"T": "char := T ● ",
		"R": "char := R ● ",
		"UNDERSCORE": "char := UNDERSCORE ● ",
		"BSLASH": "char := BSLASH ● LPAREN",
		"LBRAC": None,
		"RBRAC": ('setitems', 1),
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem := char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": "setitems := setitem setitems ● ",
		"setitem": "setitems := setitem ● ",
		"range": "setitem := range ● ",
		"\x19": None,
	},
	"setitems := setitem setitems ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"TAB": None,
		"RETURN": None,
		"N": None,
		"T": None,
		"R": None,
		"UNDERSCORE": None,
		"BSLASH": None,
		"LBRAC": None,
		"RBRAC": ('setitems', 2),
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem := range ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"RETURN": ('setitem', 1),
		"N": ('setitem', 1),
		"T": ('setitem', 1),
		"R": ('setitem', 1),
		"UNDERSCORE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"LBRAC": None,
		"RBRAC": ('setitem', 1),
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"negset := LBRAC CARET ● setitems RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"N": "char := N ● ",
		"T": "char := T ● ",
		"R": "char := R ● ",
		"UNDERSCORE": "char := UNDERSCORE ● ",
		"BSLASH": "char := BSLASH ● LPAREN",
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem := char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": "negset := LBRAC CARET setitems ● RBRAC",
		"setitem": "setitems := setitem ● ",
		"range": "setitem := range ● ",
		"\x19": None,
	},
	"negset := LBRAC CARET setitems ● RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"TAB": None,
		"RETURN": None,
		"N": None,
		"T": None,
		"R": None,
		"UNDERSCORE": None,
		"BSLASH": None,
		"LBRAC": None,
		"RBRAC": "negset := LBRAC CARET setitems RBRAC ● ",
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"negset := LBRAC CARET setitems RBRAC ● ": {
		"ALTERNATE": ('negset', 4),
		"KLEENE": ('negset', 4),
		"PLUS": ('negset', 4),
		"QUESTION": ('negset', 4),
		"LPAREN": ('negset', 4),
		"RPAREN": ('negset', 4),
		"WILDCARD": ('negset', 4),
		"CHAR": ('negset', 4),
		"NEWLINE": ('negset', 4),
		"TAB": ('negset', 4),
		"RETURN": ('negset', 4),
		"N": ('negset', 4),
		"T": ('negset', 4),
		"R": ('negset', 4),
		"UNDERSCORE": ('negset', 4),
		"BSLASH": ('negset', 4),
		"LBRAC": ('negset', 4),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('negset', 4),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"simplere := concat ● ": {
		"ALTERNATE": ('simplere', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('simplere', 1),
		"RPAREN": ('simplere', 1),
		"WILDCARD": ('simplere', 1),
		"CHAR": ('simplere', 1),
		"NEWLINE": ('simplere', 1),
		"TAB": ('simplere', 1),
		"RETURN": ('simplere', 1),
		"N": ('simplere', 1),
		"T": ('simplere', 1),
		"R": ('simplere', 1),
		"UNDERSCORE": ('simplere', 1),
		"BSLASH": ('simplere', 1),
		"LBRAC": ('simplere', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('simplere', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"simplere := basicre ● ": {
		"ALTERNATE": ('simplere', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('simplere', 1),
		"RPAREN": ('simplere', 1),
		"WILDCARD": ('simplere', 1),
		"CHAR": ('simplere', 1),
		"NEWLINE": ('simplere', 1),
		"TAB": ('simplere', 1),
		"RETURN": ('simplere', 1),
		"N": ('simplere', 1),
		"T": ('simplere', 1),
		"R": ('simplere', 1),
		"UNDERSCORE": ('simplere', 1),
		"BSLASH": ('simplere', 1),
		"LBRAC": ('simplere', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('simplere', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
}
p.start = list(p.table.keys())[0]
def action1():
    p.semstack = [RT.Split(p.semstack[1], p.semstack[0])] + p.semstack[2:]

def action2():
    p.semstack = [RT.Concat(p.semstack[1], p.semstack[0])] + p.semstack[2:]

def action3():
    p.semstack = [RT.MeanKleene(p.semstack[0])] + p.semstack[1:]

def action4():
    p.semstack = [RT.Concat(p.semstack[0], RT.MeanKleene(p.semstack[0]))] + p.semstack[1:]

def action5():
    p.semstack = [RT.Split(p.semstack[0],None)] + p.semstack[1:]

def action6():
    p.semstack = [RT.Prim(".", True)] + p.semstack

def action7():
    p.semstack = [RT.Prim(p.currentToken, False)] + p.semstack

def action8():
    p.semstack = [RT.Prim(p.currentToken[-1], False)] + p.semstack

def action9():
    n = ""
    if p.currentToken == 'n': n = '\n'
    elif p.currentToken == 't': n = '\t'
    elif p.currentToken == 'r': n = '\r'
    elif p.currentToken == '_': n = ' '
    p.semstack = [RT.Prim(n, False)] + p.semstack

def action10():
    p.semstack = [RT.CharSelect(p.semstack[0])] + p.semstack[1:]

def action11():
    items = list(set(list(map(lambda x: chr(x), range(32, 127))) + ['\n', '\t']) - set(p.semstack[0]))
    p.semstack = [RT.CharSelect(items)] + p.semstack[1:]

def action12():
    p.semstack = [p.semstack[1] + p.semstack[0]] + p.semstack[2:]

def action13():
    p.semstack = [[p.semstack[0].regex]] + p.semstack[1:]

def action14():
    char1 = p.semstack[1].regex
    char2 = p.semstack[0].regex
    if ord(char1) > ord(char2):
        raise Exception("Bad range: " + char1 + "-" + char2)
    p.semstack = [list(map(lambda x : chr(x), range(ord(char1), ord(char2)+1)))] + p.semstack[2:]

p.actions = {
	"union := re ALTERNATE simplere ● ": action1,
	"concat := simplere basicre ● ": action2,
	"star := elemre KLEENE ● ": action3,
	"plus := elemre PLUS ● ": action4,
	"question := elemre QUESTION ● ": action5,
	"any := WILDCARD ● ": action6,
	"char := CHAR ● ": action7,
	"char := NEWLINE ● ": action8,
	"char := TAB ● ": action8,
	"char := RETURN ● ": action8,
	"char := N ● ": action8,
	"char := T ● ": action8,
	"char := R ● ": action8,
	"char := UNDERSCORE ● ": action8,
	"char := BSLASH LPAREN ● ": action8,
	"char := BSLASH RPAREN ● ": action8,
	"char := BSLASH LBRAC ● ": action8,
	"char := BSLASH RBRAC ● ": action8,
	"char := BSLASH KLEENE ● ": action8,
	"char := BSLASH PLUS ● ": action8,
	"char := BSLASH QUESTION ● ": action8,
	"char := BSLASH CARET ● ": action8,
	"char := BSLASH HYPHEN ● ": action8,
	"char := BSLASH WILDCARD ● ": action8,
	"char := BSLASH ALTERNATE ● ": action8,
	"char := BSLASH BSLASH ● ": action8,
	"char := BSLASH UNDERSCORE ● ": action9,
	"char := BSLASH N ● ": action9,
	"char := BSLASH T ● ": action9,
	"char := BSLASH R ● ": action9,
	"posset := LBRAC setitems RBRAC ● ": action10,
	"negset := LBRAC CARET setitems RBRAC ● ": action11,
	"setitems := setitem setitems ● ": action12,
	"setitem := char ● ": action13,
	"range := char HYPHEN char ● ": action14,
}
