#!/usr/bin/env python3
import parser.parse as p
import RegexTree as RT

p.table = {
	"\x19 :=  ● re \x18": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": None,
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"SPACE": "char := SPACE ● ",
		"BSLASH": "char := BSLASH ● ",
		"SQUOTE": "char := SQUOTE ● ",
		"DQUOTE": "char := DQUOTE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"HYPHENCHAR": "char := HYPHENCHAR ● ",
		"WILDCARDCHAR": "char := WILDCARDCHAR ● ",
		"PLUSCHAR": "char := PLUSCHAR ● ",
		"CARETCHAR": "char := CARETCHAR ● ",
		"RPARENCHAR": "char := RPARENCHAR ● ",
		"LPARENCHAR": "char := LPARENCHAR ● ",
		"LBRACCHAR": "char := LBRACCHAR ● ",
		"RBRACCHAR": "char := RBRACCHAR ● ",
		"KLEENECHAR": "char := KLEENECHAR ● ",
		"QUESTIONCHAR": "char := QUESTIONCHAR ● ",
		"ALTERNATECHAR": "char := ALTERNATECHAR ● ",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": "\x19 := re ● \x18",
		"union": "re := union ● ",
		"simplere": "re := simplere ● ",
		"concat": "simplere := concat ● ",
		"basicre": "simplere := basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"\x19 := re ● \x18": {
		"ALTERNATE": "union := re ALTERNATE ● simplere",
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"RETURN": None,
		"HYPHENCHAR": None,
		"WILDCARDCHAR": None,
		"PLUSCHAR": None,
		"CARETCHAR": None,
		"RPARENCHAR": None,
		"LPARENCHAR": None,
		"LBRACCHAR": None,
		"RBRACCHAR": None,
		"KLEENECHAR": None,
		"QUESTIONCHAR": None,
		"ALTERNATECHAR": None,
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": "accept",
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"union := re ALTERNATE ● simplere": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": None,
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"SPACE": "char := SPACE ● ",
		"BSLASH": "char := BSLASH ● ",
		"SQUOTE": "char := SQUOTE ● ",
		"DQUOTE": "char := DQUOTE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"HYPHENCHAR": "char := HYPHENCHAR ● ",
		"WILDCARDCHAR": "char := WILDCARDCHAR ● ",
		"PLUSCHAR": "char := PLUSCHAR ● ",
		"CARETCHAR": "char := CARETCHAR ● ",
		"RPARENCHAR": "char := RPARENCHAR ● ",
		"LPARENCHAR": "char := LPARENCHAR ● ",
		"LBRACCHAR": "char := LBRACCHAR ● ",
		"RBRACCHAR": "char := RBRACCHAR ● ",
		"KLEENECHAR": "char := KLEENECHAR ● ",
		"QUESTIONCHAR": "char := QUESTIONCHAR ● ",
		"ALTERNATECHAR": "char := ALTERNATECHAR ● ",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": "union := re ALTERNATE simplere ● ",
		"concat": "simplere := concat ● ",
		"basicre": "simplere := basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"union := re ALTERNATE simplere ● ": {
		"ALTERNATE": ('union', 3),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": ('union', 3),
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"SPACE": "char := SPACE ● ",
		"BSLASH": "char := BSLASH ● ",
		"SQUOTE": "char := SQUOTE ● ",
		"DQUOTE": "char := DQUOTE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"HYPHENCHAR": "char := HYPHENCHAR ● ",
		"WILDCARDCHAR": "char := WILDCARDCHAR ● ",
		"PLUSCHAR": "char := PLUSCHAR ● ",
		"CARETCHAR": "char := CARETCHAR ● ",
		"RPARENCHAR": "char := RPARENCHAR ● ",
		"LPARENCHAR": "char := LPARENCHAR ● ",
		"LBRACCHAR": "char := LBRACCHAR ● ",
		"RBRACCHAR": "char := RBRACCHAR ● ",
		"KLEENECHAR": "char := KLEENECHAR ● ",
		"QUESTIONCHAR": "char := QUESTIONCHAR ● ",
		"ALTERNATECHAR": "char := ALTERNATECHAR ● ",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('union', 3),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": "concat := simplere basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"concat := simplere basicre ● ": {
		"ALTERNATE": ('concat', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('concat', 2),
		"RPAREN": ('concat', 2),
		"WILDCARD": ('concat', 2),
		"CHAR": ('concat', 2),
		"NEWLINE": ('concat', 2),
		"SPACE": ('concat', 2),
		"BSLASH": ('concat', 2),
		"SQUOTE": ('concat', 2),
		"DQUOTE": ('concat', 2),
		"TAB": ('concat', 2),
		"RETURN": ('concat', 2),
		"HYPHENCHAR": ('concat', 2),
		"WILDCARDCHAR": ('concat', 2),
		"PLUSCHAR": ('concat', 2),
		"CARETCHAR": ('concat', 2),
		"RPARENCHAR": ('concat', 2),
		"LPARENCHAR": ('concat', 2),
		"LBRACCHAR": ('concat', 2),
		"RBRACCHAR": ('concat', 2),
		"KLEENECHAR": ('concat', 2),
		"QUESTIONCHAR": ('concat', 2),
		"ALTERNATECHAR": ('concat', 2),
		"LBRAC": ('concat', 2),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('concat', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre := star ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"CHAR": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"SPACE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"SQUOTE": ('basicre', 1),
		"DQUOTE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"RETURN": ('basicre', 1),
		"HYPHENCHAR": ('basicre', 1),
		"WILDCARDCHAR": ('basicre', 1),
		"PLUSCHAR": ('basicre', 1),
		"CARETCHAR": ('basicre', 1),
		"RPARENCHAR": ('basicre', 1),
		"LPARENCHAR": ('basicre', 1),
		"LBRACCHAR": ('basicre', 1),
		"RBRACCHAR": ('basicre', 1),
		"KLEENECHAR": ('basicre', 1),
		"QUESTIONCHAR": ('basicre', 1),
		"ALTERNATECHAR": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre := plus ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"CHAR": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"SPACE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"SQUOTE": ('basicre', 1),
		"DQUOTE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"RETURN": ('basicre', 1),
		"HYPHENCHAR": ('basicre', 1),
		"WILDCARDCHAR": ('basicre', 1),
		"PLUSCHAR": ('basicre', 1),
		"CARETCHAR": ('basicre', 1),
		"RPARENCHAR": ('basicre', 1),
		"LPARENCHAR": ('basicre', 1),
		"LBRACCHAR": ('basicre', 1),
		"RBRACCHAR": ('basicre', 1),
		"KLEENECHAR": ('basicre', 1),
		"QUESTIONCHAR": ('basicre', 1),
		"ALTERNATECHAR": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre := question ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"CHAR": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"SPACE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"SQUOTE": ('basicre', 1),
		"DQUOTE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"RETURN": ('basicre', 1),
		"HYPHENCHAR": ('basicre', 1),
		"WILDCARDCHAR": ('basicre', 1),
		"PLUSCHAR": ('basicre', 1),
		"CARETCHAR": ('basicre', 1),
		"RPARENCHAR": ('basicre', 1),
		"LPARENCHAR": ('basicre', 1),
		"LBRACCHAR": ('basicre', 1),
		"RBRACCHAR": ('basicre', 1),
		"KLEENECHAR": ('basicre', 1),
		"QUESTIONCHAR": ('basicre', 1),
		"ALTERNATECHAR": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"basicre := elemre ● ": {
		"ALTERNATE": ('basicre', 1),
		"KLEENE": "star := elemre KLEENE ● ",
		"PLUS": "plus := elemre PLUS ● ",
		"QUESTION": "question := elemre QUESTION ● ",
		"LPAREN": ('basicre', 1),
		"RPAREN": ('basicre', 1),
		"WILDCARD": ('basicre', 1),
		"CHAR": ('basicre', 1),
		"NEWLINE": ('basicre', 1),
		"SPACE": ('basicre', 1),
		"BSLASH": ('basicre', 1),
		"SQUOTE": ('basicre', 1),
		"DQUOTE": ('basicre', 1),
		"TAB": ('basicre', 1),
		"RETURN": ('basicre', 1),
		"HYPHENCHAR": ('basicre', 1),
		"WILDCARDCHAR": ('basicre', 1),
		"PLUSCHAR": ('basicre', 1),
		"CARETCHAR": ('basicre', 1),
		"RPARENCHAR": ('basicre', 1),
		"LPARENCHAR": ('basicre', 1),
		"LBRACCHAR": ('basicre', 1),
		"RBRACCHAR": ('basicre', 1),
		"KLEENECHAR": ('basicre', 1),
		"QUESTIONCHAR": ('basicre', 1),
		"ALTERNATECHAR": ('basicre', 1),
		"LBRAC": ('basicre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('basicre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"star := elemre KLEENE ● ": {
		"ALTERNATE": ('star', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('star', 2),
		"RPAREN": ('star', 2),
		"WILDCARD": ('star', 2),
		"CHAR": ('star', 2),
		"NEWLINE": ('star', 2),
		"SPACE": ('star', 2),
		"BSLASH": ('star', 2),
		"SQUOTE": ('star', 2),
		"DQUOTE": ('star', 2),
		"TAB": ('star', 2),
		"RETURN": ('star', 2),
		"HYPHENCHAR": ('star', 2),
		"WILDCARDCHAR": ('star', 2),
		"PLUSCHAR": ('star', 2),
		"CARETCHAR": ('star', 2),
		"RPARENCHAR": ('star', 2),
		"LPARENCHAR": ('star', 2),
		"LBRACCHAR": ('star', 2),
		"RBRACCHAR": ('star', 2),
		"KLEENECHAR": ('star', 2),
		"QUESTIONCHAR": ('star', 2),
		"ALTERNATECHAR": ('star', 2),
		"LBRAC": ('star', 2),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('star', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"plus := elemre PLUS ● ": {
		"ALTERNATE": ('plus', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('plus', 2),
		"RPAREN": ('plus', 2),
		"WILDCARD": ('plus', 2),
		"CHAR": ('plus', 2),
		"NEWLINE": ('plus', 2),
		"SPACE": ('plus', 2),
		"BSLASH": ('plus', 2),
		"SQUOTE": ('plus', 2),
		"DQUOTE": ('plus', 2),
		"TAB": ('plus', 2),
		"RETURN": ('plus', 2),
		"HYPHENCHAR": ('plus', 2),
		"WILDCARDCHAR": ('plus', 2),
		"PLUSCHAR": ('plus', 2),
		"CARETCHAR": ('plus', 2),
		"RPARENCHAR": ('plus', 2),
		"LPARENCHAR": ('plus', 2),
		"LBRACCHAR": ('plus', 2),
		"RBRACCHAR": ('plus', 2),
		"KLEENECHAR": ('plus', 2),
		"QUESTIONCHAR": ('plus', 2),
		"ALTERNATECHAR": ('plus', 2),
		"LBRAC": ('plus', 2),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('plus', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"question := elemre QUESTION ● ": {
		"ALTERNATE": ('question', 2),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('question', 2),
		"RPAREN": ('question', 2),
		"WILDCARD": ('question', 2),
		"CHAR": ('question', 2),
		"NEWLINE": ('question', 2),
		"SPACE": ('question', 2),
		"BSLASH": ('question', 2),
		"SQUOTE": ('question', 2),
		"DQUOTE": ('question', 2),
		"TAB": ('question', 2),
		"RETURN": ('question', 2),
		"HYPHENCHAR": ('question', 2),
		"WILDCARDCHAR": ('question', 2),
		"PLUSCHAR": ('question', 2),
		"CARETCHAR": ('question', 2),
		"RPARENCHAR": ('question', 2),
		"LPARENCHAR": ('question', 2),
		"LBRACCHAR": ('question', 2),
		"RBRACCHAR": ('question', 2),
		"KLEENECHAR": ('question', 2),
		"QUESTIONCHAR": ('question', 2),
		"ALTERNATECHAR": ('question', 2),
		"LBRAC": ('question', 2),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('question', 2),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre := group ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"CHAR": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"RETURN": ('elemre', 1),
		"HYPHENCHAR": ('elemre', 1),
		"WILDCARDCHAR": ('elemre', 1),
		"PLUSCHAR": ('elemre', 1),
		"CARETCHAR": ('elemre', 1),
		"RPARENCHAR": ('elemre', 1),
		"LPARENCHAR": ('elemre', 1),
		"LBRACCHAR": ('elemre', 1),
		"RBRACCHAR": ('elemre', 1),
		"KLEENECHAR": ('elemre', 1),
		"QUESTIONCHAR": ('elemre', 1),
		"ALTERNATECHAR": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre := any ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"CHAR": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"RETURN": ('elemre', 1),
		"HYPHENCHAR": ('elemre', 1),
		"WILDCARDCHAR": ('elemre', 1),
		"PLUSCHAR": ('elemre', 1),
		"CARETCHAR": ('elemre', 1),
		"RPARENCHAR": ('elemre', 1),
		"LPARENCHAR": ('elemre', 1),
		"LBRACCHAR": ('elemre', 1),
		"RBRACCHAR": ('elemre', 1),
		"KLEENECHAR": ('elemre', 1),
		"QUESTIONCHAR": ('elemre', 1),
		"ALTERNATECHAR": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre := char ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"CHAR": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"RETURN": ('elemre', 1),
		"HYPHENCHAR": ('elemre', 1),
		"WILDCARDCHAR": ('elemre', 1),
		"PLUSCHAR": ('elemre', 1),
		"CARETCHAR": ('elemre', 1),
		"RPARENCHAR": ('elemre', 1),
		"LPARENCHAR": ('elemre', 1),
		"LBRACCHAR": ('elemre', 1),
		"RBRACCHAR": ('elemre', 1),
		"KLEENECHAR": ('elemre', 1),
		"QUESTIONCHAR": ('elemre', 1),
		"ALTERNATECHAR": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"elemre := set ● ": {
		"ALTERNATE": ('elemre', 1),
		"KLEENE": ('elemre', 1),
		"PLUS": ('elemre', 1),
		"QUESTION": ('elemre', 1),
		"LPAREN": ('elemre', 1),
		"RPAREN": ('elemre', 1),
		"WILDCARD": ('elemre', 1),
		"CHAR": ('elemre', 1),
		"NEWLINE": ('elemre', 1),
		"SPACE": ('elemre', 1),
		"BSLASH": ('elemre', 1),
		"SQUOTE": ('elemre', 1),
		"DQUOTE": ('elemre', 1),
		"TAB": ('elemre', 1),
		"RETURN": ('elemre', 1),
		"HYPHENCHAR": ('elemre', 1),
		"WILDCARDCHAR": ('elemre', 1),
		"PLUSCHAR": ('elemre', 1),
		"CARETCHAR": ('elemre', 1),
		"RPARENCHAR": ('elemre', 1),
		"LPARENCHAR": ('elemre', 1),
		"LBRACCHAR": ('elemre', 1),
		"RBRACCHAR": ('elemre', 1),
		"KLEENECHAR": ('elemre', 1),
		"QUESTIONCHAR": ('elemre', 1),
		"ALTERNATECHAR": ('elemre', 1),
		"LBRAC": ('elemre', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('elemre', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"set := posset ● ": {
		"ALTERNATE": ('set', 1),
		"KLEENE": ('set', 1),
		"PLUS": ('set', 1),
		"QUESTION": ('set', 1),
		"LPAREN": ('set', 1),
		"RPAREN": ('set', 1),
		"WILDCARD": ('set', 1),
		"CHAR": ('set', 1),
		"NEWLINE": ('set', 1),
		"SPACE": ('set', 1),
		"BSLASH": ('set', 1),
		"SQUOTE": ('set', 1),
		"DQUOTE": ('set', 1),
		"TAB": ('set', 1),
		"RETURN": ('set', 1),
		"HYPHENCHAR": ('set', 1),
		"WILDCARDCHAR": ('set', 1),
		"PLUSCHAR": ('set', 1),
		"CARETCHAR": ('set', 1),
		"RPARENCHAR": ('set', 1),
		"LPARENCHAR": ('set', 1),
		"LBRACCHAR": ('set', 1),
		"RBRACCHAR": ('set', 1),
		"KLEENECHAR": ('set', 1),
		"QUESTIONCHAR": ('set', 1),
		"ALTERNATECHAR": ('set', 1),
		"LBRAC": ('set', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('set', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"set := negset ● ": {
		"ALTERNATE": ('set', 1),
		"KLEENE": ('set', 1),
		"PLUS": ('set', 1),
		"QUESTION": ('set', 1),
		"LPAREN": ('set', 1),
		"RPAREN": ('set', 1),
		"WILDCARD": ('set', 1),
		"CHAR": ('set', 1),
		"NEWLINE": ('set', 1),
		"SPACE": ('set', 1),
		"BSLASH": ('set', 1),
		"SQUOTE": ('set', 1),
		"DQUOTE": ('set', 1),
		"TAB": ('set', 1),
		"RETURN": ('set', 1),
		"HYPHENCHAR": ('set', 1),
		"WILDCARDCHAR": ('set', 1),
		"PLUSCHAR": ('set', 1),
		"CARETCHAR": ('set', 1),
		"RPARENCHAR": ('set', 1),
		"LPARENCHAR": ('set', 1),
		"LBRACCHAR": ('set', 1),
		"RBRACCHAR": ('set', 1),
		"KLEENECHAR": ('set', 1),
		"QUESTIONCHAR": ('set', 1),
		"ALTERNATECHAR": ('set', 1),
		"LBRAC": ('set', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('set', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"group := LPAREN ● re RPAREN": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": None,
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"SPACE": "char := SPACE ● ",
		"BSLASH": "char := BSLASH ● ",
		"SQUOTE": "char := SQUOTE ● ",
		"DQUOTE": "char := DQUOTE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"HYPHENCHAR": "char := HYPHENCHAR ● ",
		"WILDCARDCHAR": "char := WILDCARDCHAR ● ",
		"PLUSCHAR": "char := PLUSCHAR ● ",
		"CARETCHAR": "char := CARETCHAR ● ",
		"RPARENCHAR": "char := RPARENCHAR ● ",
		"LPARENCHAR": "char := LPARENCHAR ● ",
		"LBRACCHAR": "char := LBRACCHAR ● ",
		"RBRACCHAR": "char := RBRACCHAR ● ",
		"KLEENECHAR": "char := KLEENECHAR ● ",
		"QUESTIONCHAR": "char := QUESTIONCHAR ● ",
		"ALTERNATECHAR": "char := ALTERNATECHAR ● ",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": "group := LPAREN re ● RPAREN",
		"union": "re := union ● ",
		"simplere": "re := simplere ● ",
		"concat": "simplere := concat ● ",
		"basicre": "simplere := basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"group := LPAREN re ● RPAREN": {
		"ALTERNATE": "union := re ALTERNATE ● simplere",
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": "group := LPAREN re RPAREN ● ",
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"RETURN": None,
		"HYPHENCHAR": None,
		"WILDCARDCHAR": None,
		"PLUSCHAR": None,
		"CARETCHAR": None,
		"RPARENCHAR": None,
		"LPARENCHAR": None,
		"LBRACCHAR": None,
		"RBRACCHAR": None,
		"KLEENECHAR": None,
		"QUESTIONCHAR": None,
		"ALTERNATECHAR": None,
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"group := LPAREN re RPAREN ● ": {
		"ALTERNATE": ('group', 3),
		"KLEENE": ('group', 3),
		"PLUS": ('group', 3),
		"QUESTION": ('group', 3),
		"LPAREN": ('group', 3),
		"RPAREN": ('group', 3),
		"WILDCARD": ('group', 3),
		"CHAR": ('group', 3),
		"NEWLINE": ('group', 3),
		"SPACE": ('group', 3),
		"BSLASH": ('group', 3),
		"SQUOTE": ('group', 3),
		"DQUOTE": ('group', 3),
		"TAB": ('group', 3),
		"RETURN": ('group', 3),
		"HYPHENCHAR": ('group', 3),
		"WILDCARDCHAR": ('group', 3),
		"PLUSCHAR": ('group', 3),
		"CARETCHAR": ('group', 3),
		"RPARENCHAR": ('group', 3),
		"LPARENCHAR": ('group', 3),
		"LBRACCHAR": ('group', 3),
		"RBRACCHAR": ('group', 3),
		"KLEENECHAR": ('group', 3),
		"QUESTIONCHAR": ('group', 3),
		"ALTERNATECHAR": ('group', 3),
		"LBRAC": ('group', 3),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('group', 3),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"re := union ● ": {
		"ALTERNATE": ('re', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": ('re', 1),
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"RETURN": None,
		"HYPHENCHAR": None,
		"WILDCARDCHAR": None,
		"PLUSCHAR": None,
		"CARETCHAR": None,
		"RPARENCHAR": None,
		"LPARENCHAR": None,
		"LBRACCHAR": None,
		"RBRACCHAR": None,
		"KLEENECHAR": None,
		"QUESTIONCHAR": None,
		"ALTERNATECHAR": None,
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('re', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"re := simplere ● ": {
		"ALTERNATE": ('re', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": "group := LPAREN ● re RPAREN",
		"RPAREN": ('re', 1),
		"WILDCARD": "any := WILDCARD ● ",
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"SPACE": "char := SPACE ● ",
		"BSLASH": "char := BSLASH ● ",
		"SQUOTE": "char := SQUOTE ● ",
		"DQUOTE": "char := DQUOTE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"HYPHENCHAR": "char := HYPHENCHAR ● ",
		"WILDCARDCHAR": "char := WILDCARDCHAR ● ",
		"PLUSCHAR": "char := PLUSCHAR ● ",
		"CARETCHAR": "char := CARETCHAR ● ",
		"RPARENCHAR": "char := RPARENCHAR ● ",
		"LPARENCHAR": "char := LPARENCHAR ● ",
		"LBRACCHAR": "char := LBRACCHAR ● ",
		"RBRACCHAR": "char := RBRACCHAR ● ",
		"KLEENECHAR": "char := KLEENECHAR ● ",
		"QUESTIONCHAR": "char := QUESTIONCHAR ● ",
		"ALTERNATECHAR": "char := ALTERNATECHAR ● ",
		"LBRAC": "posset := LBRAC ● setitems RBRAC",
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('re', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": "concat := simplere basicre ● ",
		"star": "basicre := star ● ",
		"plus": "basicre := plus ● ",
		"question": "basicre := question ● ",
		"elemre": "basicre := elemre ● ",
		"group": "elemre := group ● ",
		"any": "elemre := any ● ",
		"char": "elemre := char ● ",
		"set": "elemre := set ● ",
		"posset": "set := posset ● ",
		"negset": "set := negset ● ",
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"any := WILDCARD ● ": {
		"ALTERNATE": ('any', 1),
		"KLEENE": ('any', 1),
		"PLUS": ('any', 1),
		"QUESTION": ('any', 1),
		"LPAREN": ('any', 1),
		"RPAREN": ('any', 1),
		"WILDCARD": ('any', 1),
		"CHAR": ('any', 1),
		"NEWLINE": ('any', 1),
		"SPACE": ('any', 1),
		"BSLASH": ('any', 1),
		"SQUOTE": ('any', 1),
		"DQUOTE": ('any', 1),
		"TAB": ('any', 1),
		"RETURN": ('any', 1),
		"HYPHENCHAR": ('any', 1),
		"WILDCARDCHAR": ('any', 1),
		"PLUSCHAR": ('any', 1),
		"CARETCHAR": ('any', 1),
		"RPARENCHAR": ('any', 1),
		"LPARENCHAR": ('any', 1),
		"LBRACCHAR": ('any', 1),
		"RBRACCHAR": ('any', 1),
		"KLEENECHAR": ('any', 1),
		"QUESTIONCHAR": ('any', 1),
		"ALTERNATECHAR": ('any', 1),
		"LBRAC": ('any', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('any', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := CHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := NEWLINE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := SPACE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := BSLASH ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := SQUOTE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := DQUOTE ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := TAB ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := RETURN ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := HYPHENCHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := WILDCARDCHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := PLUSCHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := CARETCHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := RPARENCHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := LPARENCHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := LBRACCHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := RBRACCHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := KLEENECHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := QUESTIONCHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"char := ALTERNATECHAR ● ": {
		"ALTERNATE": ('char', 1),
		"KLEENE": ('char', 1),
		"PLUS": ('char', 1),
		"QUESTION": ('char', 1),
		"LPAREN": ('char', 1),
		"RPAREN": ('char', 1),
		"WILDCARD": ('char', 1),
		"CHAR": ('char', 1),
		"NEWLINE": ('char', 1),
		"SPACE": ('char', 1),
		"BSLASH": ('char', 1),
		"SQUOTE": ('char', 1),
		"DQUOTE": ('char', 1),
		"TAB": ('char', 1),
		"RETURN": ('char', 1),
		"HYPHENCHAR": ('char', 1),
		"WILDCARDCHAR": ('char', 1),
		"PLUSCHAR": ('char', 1),
		"CARETCHAR": ('char', 1),
		"RPARENCHAR": ('char', 1),
		"LPARENCHAR": ('char', 1),
		"LBRACCHAR": ('char', 1),
		"RBRACCHAR": ('char', 1),
		"KLEENECHAR": ('char', 1),
		"QUESTIONCHAR": ('char', 1),
		"ALTERNATECHAR": ('char', 1),
		"LBRAC": ('char', 1),
		"RBRAC": ('char', 1),
		"CARET": None,
		"HYPHEN": ('char', 1),
		"\x18": ('char', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"posset := LBRAC ● setitems RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"SPACE": "char := SPACE ● ",
		"BSLASH": "char := BSLASH ● ",
		"SQUOTE": "char := SQUOTE ● ",
		"DQUOTE": "char := DQUOTE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"HYPHENCHAR": "char := HYPHENCHAR ● ",
		"WILDCARDCHAR": "char := WILDCARDCHAR ● ",
		"PLUSCHAR": "char := PLUSCHAR ● ",
		"CARETCHAR": "char := CARETCHAR ● ",
		"RPARENCHAR": "char := RPARENCHAR ● ",
		"LPARENCHAR": "char := LPARENCHAR ● ",
		"LBRACCHAR": "char := LBRACCHAR ● ",
		"RBRACCHAR": "char := RBRACCHAR ● ",
		"KLEENECHAR": "char := KLEENECHAR ● ",
		"QUESTIONCHAR": "char := QUESTIONCHAR ● ",
		"ALTERNATECHAR": "char := ALTERNATECHAR ● ",
		"LBRAC": None,
		"RBRAC": None,
		"CARET": "negset := LBRAC CARET ● setitems RBRAC",
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem := char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": "posset := LBRAC setitems ● RBRAC",
		"setitem": "setitems := setitem ● ",
		"range": "setitem := range ● ",
		"\x19": None,
	},
	"setitem := char ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"RETURN": ('setitem', 1),
		"HYPHENCHAR": ('setitem', 1),
		"WILDCARDCHAR": ('setitem', 1),
		"PLUSCHAR": ('setitem', 1),
		"CARETCHAR": ('setitem', 1),
		"RPARENCHAR": ('setitem', 1),
		"LPARENCHAR": ('setitem', 1),
		"LBRACCHAR": ('setitem', 1),
		"RBRACCHAR": ('setitem', 1),
		"KLEENECHAR": ('setitem', 1),
		"QUESTIONCHAR": ('setitem', 1),
		"ALTERNATECHAR": ('setitem', 1),
		"LBRAC": None,
		"RBRAC": ('setitem', 1),
		"CARET": None,
		"HYPHEN": "range := char HYPHEN ● char",
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"range := char HYPHEN ● char": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"SPACE": "char := SPACE ● ",
		"BSLASH": "char := BSLASH ● ",
		"SQUOTE": "char := SQUOTE ● ",
		"DQUOTE": "char := DQUOTE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"HYPHENCHAR": "char := HYPHENCHAR ● ",
		"WILDCARDCHAR": "char := WILDCARDCHAR ● ",
		"PLUSCHAR": "char := PLUSCHAR ● ",
		"CARETCHAR": "char := CARETCHAR ● ",
		"RPARENCHAR": "char := RPARENCHAR ● ",
		"LPARENCHAR": "char := LPARENCHAR ● ",
		"LBRACCHAR": "char := LBRACCHAR ● ",
		"RBRACCHAR": "char := RBRACCHAR ● ",
		"KLEENECHAR": "char := KLEENECHAR ● ",
		"QUESTIONCHAR": "char := QUESTIONCHAR ● ",
		"ALTERNATECHAR": "char := ALTERNATECHAR ● ",
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "range := char HYPHEN char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"range := char HYPHEN char ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": ('range', 3),
		"NEWLINE": ('range', 3),
		"SPACE": ('range', 3),
		"BSLASH": ('range', 3),
		"SQUOTE": ('range', 3),
		"DQUOTE": ('range', 3),
		"TAB": ('range', 3),
		"RETURN": ('range', 3),
		"HYPHENCHAR": ('range', 3),
		"WILDCARDCHAR": ('range', 3),
		"PLUSCHAR": ('range', 3),
		"CARETCHAR": ('range', 3),
		"RPARENCHAR": ('range', 3),
		"LPARENCHAR": ('range', 3),
		"LBRACCHAR": ('range', 3),
		"RBRACCHAR": ('range', 3),
		"KLEENECHAR": ('range', 3),
		"QUESTIONCHAR": ('range', 3),
		"ALTERNATECHAR": ('range', 3),
		"LBRAC": None,
		"RBRAC": ('range', 3),
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"posset := LBRAC setitems ● RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"RETURN": None,
		"HYPHENCHAR": None,
		"WILDCARDCHAR": None,
		"PLUSCHAR": None,
		"CARETCHAR": None,
		"RPARENCHAR": None,
		"LPARENCHAR": None,
		"LBRACCHAR": None,
		"RBRACCHAR": None,
		"KLEENECHAR": None,
		"QUESTIONCHAR": None,
		"ALTERNATECHAR": None,
		"LBRAC": None,
		"RBRAC": "posset := LBRAC setitems RBRAC ● ",
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"posset := LBRAC setitems RBRAC ● ": {
		"ALTERNATE": ('posset', 3),
		"KLEENE": ('posset', 3),
		"PLUS": ('posset', 3),
		"QUESTION": ('posset', 3),
		"LPAREN": ('posset', 3),
		"RPAREN": ('posset', 3),
		"WILDCARD": ('posset', 3),
		"CHAR": ('posset', 3),
		"NEWLINE": ('posset', 3),
		"SPACE": ('posset', 3),
		"BSLASH": ('posset', 3),
		"SQUOTE": ('posset', 3),
		"DQUOTE": ('posset', 3),
		"TAB": ('posset', 3),
		"RETURN": ('posset', 3),
		"HYPHENCHAR": ('posset', 3),
		"WILDCARDCHAR": ('posset', 3),
		"PLUSCHAR": ('posset', 3),
		"CARETCHAR": ('posset', 3),
		"RPARENCHAR": ('posset', 3),
		"LPARENCHAR": ('posset', 3),
		"LBRACCHAR": ('posset', 3),
		"RBRACCHAR": ('posset', 3),
		"KLEENECHAR": ('posset', 3),
		"QUESTIONCHAR": ('posset', 3),
		"ALTERNATECHAR": ('posset', 3),
		"LBRAC": ('posset', 3),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('posset', 3),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"setitems := setitem ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"SPACE": "char := SPACE ● ",
		"BSLASH": "char := BSLASH ● ",
		"SQUOTE": "char := SQUOTE ● ",
		"DQUOTE": "char := DQUOTE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"HYPHENCHAR": "char := HYPHENCHAR ● ",
		"WILDCARDCHAR": "char := WILDCARDCHAR ● ",
		"PLUSCHAR": "char := PLUSCHAR ● ",
		"CARETCHAR": "char := CARETCHAR ● ",
		"RPARENCHAR": "char := RPARENCHAR ● ",
		"LPARENCHAR": "char := LPARENCHAR ● ",
		"LBRACCHAR": "char := LBRACCHAR ● ",
		"RBRACCHAR": "char := RBRACCHAR ● ",
		"KLEENECHAR": "char := KLEENECHAR ● ",
		"QUESTIONCHAR": "char := QUESTIONCHAR ● ",
		"ALTERNATECHAR": "char := ALTERNATECHAR ● ",
		"LBRAC": None,
		"RBRAC": ('setitems', 1),
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem := char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": "setitems := setitem setitems ● ",
		"setitem": "setitems := setitem ● ",
		"range": "setitem := range ● ",
		"\x19": None,
	},
	"setitems := setitem setitems ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"RETURN": None,
		"HYPHENCHAR": None,
		"WILDCARDCHAR": None,
		"PLUSCHAR": None,
		"CARETCHAR": None,
		"RPARENCHAR": None,
		"LPARENCHAR": None,
		"LBRACCHAR": None,
		"RBRACCHAR": None,
		"KLEENECHAR": None,
		"QUESTIONCHAR": None,
		"ALTERNATECHAR": None,
		"LBRAC": None,
		"RBRAC": ('setitems', 2),
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"setitem := range ● ": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": ('setitem', 1),
		"NEWLINE": ('setitem', 1),
		"SPACE": ('setitem', 1),
		"BSLASH": ('setitem', 1),
		"SQUOTE": ('setitem', 1),
		"DQUOTE": ('setitem', 1),
		"TAB": ('setitem', 1),
		"RETURN": ('setitem', 1),
		"HYPHENCHAR": ('setitem', 1),
		"WILDCARDCHAR": ('setitem', 1),
		"PLUSCHAR": ('setitem', 1),
		"CARETCHAR": ('setitem', 1),
		"RPARENCHAR": ('setitem', 1),
		"LPARENCHAR": ('setitem', 1),
		"LBRACCHAR": ('setitem', 1),
		"RBRACCHAR": ('setitem', 1),
		"KLEENECHAR": ('setitem', 1),
		"QUESTIONCHAR": ('setitem', 1),
		"ALTERNATECHAR": ('setitem', 1),
		"LBRAC": None,
		"RBRAC": ('setitem', 1),
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"negset := LBRAC CARET ● setitems RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": "char := CHAR ● ",
		"NEWLINE": "char := NEWLINE ● ",
		"SPACE": "char := SPACE ● ",
		"BSLASH": "char := BSLASH ● ",
		"SQUOTE": "char := SQUOTE ● ",
		"DQUOTE": "char := DQUOTE ● ",
		"TAB": "char := TAB ● ",
		"RETURN": "char := RETURN ● ",
		"HYPHENCHAR": "char := HYPHENCHAR ● ",
		"WILDCARDCHAR": "char := WILDCARDCHAR ● ",
		"PLUSCHAR": "char := PLUSCHAR ● ",
		"CARETCHAR": "char := CARETCHAR ● ",
		"RPARENCHAR": "char := RPARENCHAR ● ",
		"LPARENCHAR": "char := LPARENCHAR ● ",
		"LBRACCHAR": "char := LBRACCHAR ● ",
		"RBRACCHAR": "char := RBRACCHAR ● ",
		"KLEENECHAR": "char := KLEENECHAR ● ",
		"QUESTIONCHAR": "char := QUESTIONCHAR ● ",
		"ALTERNATECHAR": "char := ALTERNATECHAR ● ",
		"LBRAC": None,
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": "setitem := char ● ",
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": "negset := LBRAC CARET setitems ● RBRAC",
		"setitem": "setitems := setitem ● ",
		"range": "setitem := range ● ",
		"\x19": None,
	},
	"negset := LBRAC CARET setitems ● RBRAC": {
		"ALTERNATE": None,
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": None,
		"RPAREN": None,
		"WILDCARD": None,
		"CHAR": None,
		"NEWLINE": None,
		"SPACE": None,
		"BSLASH": None,
		"SQUOTE": None,
		"DQUOTE": None,
		"TAB": None,
		"RETURN": None,
		"HYPHENCHAR": None,
		"WILDCARDCHAR": None,
		"PLUSCHAR": None,
		"CARETCHAR": None,
		"RPARENCHAR": None,
		"LPARENCHAR": None,
		"LBRACCHAR": None,
		"RBRACCHAR": None,
		"KLEENECHAR": None,
		"QUESTIONCHAR": None,
		"ALTERNATECHAR": None,
		"LBRAC": None,
		"RBRAC": "negset := LBRAC CARET setitems RBRAC ● ",
		"CARET": None,
		"HYPHEN": None,
		"\x18": None,
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"negset := LBRAC CARET setitems RBRAC ● ": {
		"ALTERNATE": ('negset', 4),
		"KLEENE": ('negset', 4),
		"PLUS": ('negset', 4),
		"QUESTION": ('negset', 4),
		"LPAREN": ('negset', 4),
		"RPAREN": ('negset', 4),
		"WILDCARD": ('negset', 4),
		"CHAR": ('negset', 4),
		"NEWLINE": ('negset', 4),
		"SPACE": ('negset', 4),
		"BSLASH": ('negset', 4),
		"SQUOTE": ('negset', 4),
		"DQUOTE": ('negset', 4),
		"TAB": ('negset', 4),
		"RETURN": ('negset', 4),
		"HYPHENCHAR": ('negset', 4),
		"WILDCARDCHAR": ('negset', 4),
		"PLUSCHAR": ('negset', 4),
		"CARETCHAR": ('negset', 4),
		"RPARENCHAR": ('negset', 4),
		"LPARENCHAR": ('negset', 4),
		"LBRACCHAR": ('negset', 4),
		"RBRACCHAR": ('negset', 4),
		"KLEENECHAR": ('negset', 4),
		"QUESTIONCHAR": ('negset', 4),
		"ALTERNATECHAR": ('negset', 4),
		"LBRAC": ('negset', 4),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('negset', 4),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"simplere := concat ● ": {
		"ALTERNATE": ('simplere', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('simplere', 1),
		"RPAREN": ('simplere', 1),
		"WILDCARD": ('simplere', 1),
		"CHAR": ('simplere', 1),
		"NEWLINE": ('simplere', 1),
		"SPACE": ('simplere', 1),
		"BSLASH": ('simplere', 1),
		"SQUOTE": ('simplere', 1),
		"DQUOTE": ('simplere', 1),
		"TAB": ('simplere', 1),
		"RETURN": ('simplere', 1),
		"HYPHENCHAR": ('simplere', 1),
		"WILDCARDCHAR": ('simplere', 1),
		"PLUSCHAR": ('simplere', 1),
		"CARETCHAR": ('simplere', 1),
		"RPARENCHAR": ('simplere', 1),
		"LPARENCHAR": ('simplere', 1),
		"LBRACCHAR": ('simplere', 1),
		"RBRACCHAR": ('simplere', 1),
		"KLEENECHAR": ('simplere', 1),
		"QUESTIONCHAR": ('simplere', 1),
		"ALTERNATECHAR": ('simplere', 1),
		"LBRAC": ('simplere', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('simplere', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
	"simplere := basicre ● ": {
		"ALTERNATE": ('simplere', 1),
		"KLEENE": None,
		"PLUS": None,
		"QUESTION": None,
		"LPAREN": ('simplere', 1),
		"RPAREN": ('simplere', 1),
		"WILDCARD": ('simplere', 1),
		"CHAR": ('simplere', 1),
		"NEWLINE": ('simplere', 1),
		"SPACE": ('simplere', 1),
		"BSLASH": ('simplere', 1),
		"SQUOTE": ('simplere', 1),
		"DQUOTE": ('simplere', 1),
		"TAB": ('simplere', 1),
		"RETURN": ('simplere', 1),
		"HYPHENCHAR": ('simplere', 1),
		"WILDCARDCHAR": ('simplere', 1),
		"PLUSCHAR": ('simplere', 1),
		"CARETCHAR": ('simplere', 1),
		"RPARENCHAR": ('simplere', 1),
		"LPARENCHAR": ('simplere', 1),
		"LBRACCHAR": ('simplere', 1),
		"RBRACCHAR": ('simplere', 1),
		"KLEENECHAR": ('simplere', 1),
		"QUESTIONCHAR": ('simplere', 1),
		"ALTERNATECHAR": ('simplere', 1),
		"LBRAC": ('simplere', 1),
		"RBRAC": None,
		"CARET": None,
		"HYPHEN": None,
		"\x18": ('simplere', 1),
		"re": None,
		"union": None,
		"simplere": None,
		"concat": None,
		"basicre": None,
		"star": None,
		"plus": None,
		"question": None,
		"elemre": None,
		"group": None,
		"any": None,
		"char": None,
		"set": None,
		"posset": None,
		"negset": None,
		"setitems": None,
		"setitem": None,
		"range": None,
		"\x19": None,
	},
}
p.start = list(p.table.keys())[0]
def action1():
    p.semstack = [RT.Split(p.semstack[1], p.semstack[0])] + p.semstack[2:]

def action2():
    p.semstack = [RT.Concat(p.semstack[1], p.semstack[0])] + p.semstack[2:]

def action3():
    p.semstack = [RT.MeanKleene(p.semstack[0])] + p.semstack[1:]

def action4():
    p.semstack = [RT.Concat(p.semstack[0], RT.MeanKleene(p.semstack[0]))] + p.semstack[1:]

def action5():
    p.semstack = [RT.Split(p.semstack[0],None)] + p.semstack[1:]

def action6():
    p.semstack = [RT.Prim(".", True)] + p.semstack

def action7():
    p.semstack = [RT.Prim(p.currentToken, False)] + p.semstack

def action8():
    p.semstack = [RT.CharSelect(p.semstack[0])] + p.semstack[1:]

def action9():
    items = list(set(list(map(lambda x: chr(x), range(32, 127))) + ['\n', '\t']) - set(p.semstack[0]))
    p.semstack = [RT.CharSelect(items)] + p.semstack[1:]

def action10():
    p.semstack = [p.semstack[1] + p.semstack[0]] + p.semstack[2:]

def action11():
    p.semstack = [[p.semstack[0].regex]] + p.semstack[1:]

def action12():
    char1 = p.semstack[1].regex
    char2 = p.semstack[0].regex
    if ord(char1) > ord(char2):
        raise Exception("Bad range: " + char1 + "-" + char2)
    p.semstack = [list(map(lambda x : chr(x), range(ord(char1), ord(char2)+1)))] + p.semstack[2:]

p.actions = {
	"union := re ALTERNATE simplere ● ": action1,
	"concat := simplere basicre ● ": action2,
	"star := elemre KLEENE ● ": action3,
	"plus := elemre PLUS ● ": action4,
	"question := elemre QUESTION ● ": action5,
	"any := WILDCARD ● ": action6,
	"char := CHAR ● ": action7,
	"char := NEWLINE ● ": action7,
	"char := SPACE ● ": action7,
	"char := BSLASH ● ": action7,
	"char := SQUOTE ● ": action7,
	"char := DQUOTE ● ": action7,
	"char := TAB ● ": action7,
	"char := RETURN ● ": action7,
	"char := HYPHENCHAR ● ": action7,
	"char := WILDCARDCHAR ● ": action7,
	"char := PLUSCHAR ● ": action7,
	"char := CARETCHAR ● ": action7,
	"char := RPARENCHAR ● ": action7,
	"char := LPARENCHAR ● ": action7,
	"char := LBRACCHAR ● ": action7,
	"char := RBRACCHAR ● ": action7,
	"char := KLEENECHAR ● ": action7,
	"char := QUESTIONCHAR ● ": action7,
	"char := ALTERNATECHAR ● ": action7,
	"posset := LBRAC setitems RBRAC ● ": action8,
	"negset := LBRAC CARET setitems RBRAC ● ": action9,
	"setitems := setitem setitems ● ": action10,
	"setitem := char ● ": action11,
	"range := char HYPHEN char ● ": action12,
}
