\( LPAREN false
\) RPAREN false
\[ LBRAC false
\] RBRAC false
\* KLEENE false
\? QUESTION false
\+ PLUS false
\^ CARET false
\| ALTERNATE false
\- HYPHEN false
\\n NEWLINE true
\\_ SPACE true
\\\\ BSLASH true
\\' SQUOTE true
\\" DQUOTE true
\\t TAB true
\\r RETURN true
\. WILDCARD false
\\\. WILDCARDCHAR true
\\\+ PLUSCHAR true
\\\^ CARETCHAR true
\\\) RPARENCHAR true
\\\( LPARENCHAR true
\\\- HYPHENCHAR true
\\\[ LBRACCHAR true
\\\] RBRACCHAR true
\\\* KLEENECHAR true
\\\? QUESTIONCHAR true
\\\| ALTERNATECHAR true
[^\^\*\+\?\|\.\(\)\-\\\n\t\r] CHAR true
\_|\t|\n|\r (SKIP)
. (ERR) "Bad input"